# Netlify Build Configuration
[build]
  publish = "baconfort-react/dist"
  command = "cd baconfort-react && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://tu-backend-railway.up.railway.app"

# Variables de entorno para el build
# VITE_API_URL se actualizará con la URL de Railway

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
